require 'nokogiri'
require 'open-uri'
require 'colorize'
require 'remedy'
require 'pry'
require_relative '../classes/GameSearchResult'
require_relative '../classes/Tag'
# require_relative '../classes/CLI'
require_relative '../classes/cli'
require_relative '../classes/SteamStoreScraper'
require_relative '../classes/StorePageController'
require_relative '../classes/RemedyCli'
require_relative '../classes/Searcher'
require_relative '../classes/ResultsNavigator'
require_relative '../classes/Developer'
